### ISSUE TITLE
Nom des fichiers

### ISSUE THREAD

**Issue by Anahide64** [PSL-Chartes-HTR-Students/HN2021-Kovalewsky-1893#3]
Hello, je me disais qu'on pourrait choisir comment nommer nos fichiers cet après-midi. Qu'en pensez-vous ?

**Comment by zoeleveque** [comment]
Bonsoir Anahide, je suis désolée de la réponse tardive de nouveau, au final, je n'ai pas pu me libérer pour en discuter. As-tu une idée de la manière dont on pourrait présenter les choses ? Si on exporte d'eScriptorium à la fois les transcriptions en XML Alto et les images correspondantes, il faudrait peut-être trouver un nom concordant pour les deux, de manière à pouvoir les retrouver et les associer facilement. A moins de laisser leurs noms d'origine ? Qu'en penses-tu ? Kate, tu as peut-être une autre idée ?

**Comment by Anahide64** [comment]
Salut Zoé, pas de soucis :)  On pourrait partir sur le format "MK_1893_2_numéro de page" (=Maxime Kovalewksy, date de publication, numéro du chapitre) et l'extension permettra de différencier texte et image. Qu'en penses-tu ?

**Comment by zoeleveque** [comment]
C'est ok pour moi :) Quand tu parles d'extension, c'est par exemple .xmlalto pour les transcriptions et .png pour les images ? Ou juste .xml pour les textes ?
